routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('graph');
});
Route::get('/graph', function () {
    return view('graph');
})->name('graph')->middleware('auth');
Route::resource('survey', 'SurveyController')->middleware('auth');
Route::get('/survey/{action}/{id}', 'SurveyController@validasi')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Gender.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gender extends Model
{
    protected $table ='gender';
    public function survey()
    {
        return $this->hasMany('App\Survey', 'gender_id', 'id');
    }
}

app/Status.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $table ='status';
    public function survey()
    {
        return $this->hasMany('App\Survey', 'status_id', 'id');
    }
}

app/Study.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Study extends Model
{
    protected $table ='study';
    public function survey()
    {
        return $this->hasMany('App\Survey', 'study_id', 'id');
    }
}

app/Survey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    protected $table ='survey';
    public $timestamps = false;
    protected $fillable = [
        'id', 'nama', 'tanggal', 'gender_id', 'study_id', 'status_id', 'nik'
    ];
    public function gender()
    {
        return $this->belongsTo('App\Gender', 'gender_id');
    }
    public function status()
    {
        return $this->belongsTo('App\Status', 'status_id');
    }
    public function study()
    {
        return $this->belongsTo('App\Study', 'study_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Survey;
use App\Gender;
use App\Study;

use DB;

class SurveyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $survey = Survey::all();
        return view('survey', compact('survey'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $survey = new Survey();
        $component = $this->initComponent();
        $method = 2 ;
        $action = route('survey.index');
        return view('add-survey', compact('component', 'method', 'action', 'survey'));
    }

    public function initComponent(){
        $data = new \StdClass();
        $data->gender= Gender::all();
        $data->study= Study::all();
        return $data;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $survey = new Survey();
        $survey->nama=$request->nama;
        $survey->nik=$request->nik;
        $survey->tanggal=strtotime($request->tanggal);
        $survey->gender_id=$request->gender;
        $survey->study_id=$request->study;
        $survey->status_id=1;
        if($survey->save()){
            return redirect('/survey');
        }
        return 'failed';
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $survey = Survey::where('id', $id)->with('gender', 'status', 'study')->get()->first();
        $survey->tanggal = date('d M Y', $survey->tanggal);
        return $survey;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $survey = Survey::find($id);
        $survey->tanggal = date('Y-m-d', $survey->tanggal);
        $component = $this->initComponent();
        $method = 1 ;
        $action = route('survey.update', $id);
        return view('add-survey', compact('component', 'method', 'action', 'survey'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $survey = Survey::find($id);
        $survey->nama=$request->nama;
        $survey->nik=$request->nik;
        $survey->tanggal=strtotime($request->tanggal);
        $survey->gender_id=$request->gender;
        $survey->study_id=$request->study;
        if($survey->save()){
            return redirect('/survey');
        }
        return 'failed';
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function validasi($action,$id){
        $survey = Survey::find($id);
        $survey->status_id=$action;
        if($survey->save()){
            return redirect('/survey');
        }
        return 'failed';
    }

    public function surveyGraph($filter){
        if($filter == 1){
            $survey = Survey::select('gender_id', DB::raw('count(*) as total'))->groupBy('gender_id')->get();

        }else{
            $survey = Survey::select('gender_id', DB::raw('count(*) as total'))->groupBy('gender_id')->get();
        }
        return response()->json($survey);
    }
}

resources/views/add-survey.blade.php
@extends('main', ['currentMenu' => 'mn-survey'])
@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div>Data Survey
                <div class="page-title-subheading">
                    Your personal data bellow
                </div>
            </div>
        </div> 
</div>
</div>            
<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Details Survey</h5>
        <form action="{{$action}}" method="post" class="needs-validation" novalidate>
            @if($method == 1)
                @method('PUT')
            @endif
            @csrf
            <div class="position-relative row form-group">
                <label for="in-su-nama" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input name="nama" id="in-su-nama" placeholder="" 
                    type="text" class="form-control form-control-sm" value="{{$survey->nama}}" required>
                </div>
            </div>
            <div class="position-relative row form-group">
                <label for="in-su-nik" class="col-sm-2 col-form-label">NIK</label>
                <div class="col-sm-10">
                    <input name="nik" id="in-su-nik" placeholder="" 
                    type="number" class="form-control form-control-sm" value="{{$survey->nik}}" required>
                </div>
            </div>
            <div class="position-relative row form-group">
                <label for="in-su-tgl" class="col-sm-2 col-form-label">Tanggal Lahir</label>
                <div class="col-sm-10">
                    <input name="tanggal" id="in-su-tgl" placeholder="" 
                    type="date" class="form-control form-control-sm" value="{{$survey->tanggal}}" required>
                </div>
            </div>
            <div class="position-relative row form-group">
                <label for="sel-gen" class="col-sm-2 col-form-label">Gender</label>
                <div class="col-sm-10">
                    <select name="gender" id="sel-gen" class="chosen form-control form-control-sm">
                        @foreach($component->gender as $gen)
                            @if($survey->gender && $survey->gender->id == $gen->id)
                                <option value="{{$gen->id}}" selected>{{$gen->description}}</option>
                            @else
                                <option value="{{$gen->id}}">{{$gen->description}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="position-relative row form-group">
                <label for="sel-std" class="col-sm-2 col-form-label">Pendidikan Terakhir</label>
                <div class="col-sm-10">
                    <select name="study" id="sel-std" class="chosen form-control form-control-sm">
                        @foreach($component->study as $std)
                            @if($survey->study && $survey->study->id == $std->id)
                                <option value="{{$std->id}}" selected>{{$std->description}}</option>
                            @else
                                <option value="{{$std->id}}">{{$std->description}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                    <label class="form-check-label" for="invalidCheck">
                        I have correctly entered the data. 
                    </label>
                    <div class="invalid-feedback">
                        You must agree before submitting.
                    </div>
                </div>
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>

        <script>
            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function() {
                'use strict';
                window.addEventListener('load', function() {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');
                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function(form) {
                        form.addEventListener('submit', function(event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>
    </div>
</div>
@endsection

resources/views/graph.blade.php
@extends('main', ['currentMenu' => 'mn-graph'])
@section('content')
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>Data Survey</div>
                </div>   
            </div>
        </div>            
        <div class="row">
            <div class="col-md-12 col-xl-12">
                <div class="card mb-3 widget-content bg-midnight-bloom">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Grafik</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">Survey by Year 
                        
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <canvas id="graph-1" width="200" height="100"></canvas>
                        </div>
                    </div>
                </div>
                <div class="main-card mb-3 card">
                    <div class="card-header">Survey by Gender
                        
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <canvas id="graph-2" width="200" height="100"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/modals/details-survey.blade.php
<div class="modal fade detail-survey" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Details Survey</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="main-card mb-12 card">
                            <div class="card-body">
                                <h5 class="card-title">Survey</h5>
                                <div class="row">
                                    <div class="col-md-6">
                                        <p class="active list-group-item-action list-group-item">Name</p>
                                        <p class="list-group-item-action list-group-item su-nama"></p>
                                        <p class="active list-group-item-action list-group-item">NIK</p>
                                        <p class="list-group-item-action list-group-item su-nik"></p>
                                        <p class="active list-group-item-action list-group-item">Tanggal Lahir</p>
                                        <p class="list-group-item-action list-group-item su-tgl"></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="active list-group-item-action list-group-item">Gender</p>
                                        <p class="list-group-item-action list-group-item su-gen"></p>
                                        <p class="active list-group-item-action list-group-item">Pendidikan Terakhir</p>
                                        <p class="list-group-item-action list-group-item su-std"></p>
                                        <p class="active list-group-item-action list-group-item">Status</p>
                                        <p class="list-group-item-action list-group-item su-status pl-3 badge badge-focus"></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                @if(Auth::user() && Auth::user()->role_id == 1)
                    <button type="button" class="btn btn-danger set-id su-reject">Reject</button>
                    <button type="button" class="btn btn-success set-id su-approve">Approve</button>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/survey.blade.php
@extends('main', ['currentMenu' => 'mn-survey'])
@section('content')
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>Data Survey</div>
                </div>   
            </div>
        </div>            
        <div class="row">
            <div class="col-md-12 col-xl-12">
                <div class="card mb-3 widget-content bg-midnight-bloom">
                    <div class="widget-content-wrapper text-white">
                        <div class="widget-content-left">
                            <div class="widget-heading">Total Survey</div>
                        </div>
                        <div class="widget-content-right">
                            <div class="widget-numbers text-white"><span>{{count($survey)}}</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">Survey 
                        @if(Auth::user() && Auth::user()->role_id == 2)
                        <a href="{{route('survey.create')}}" class="btn btn-primary ml-auto"><i class="fa fa-plus-circle"></i> Add Survey</a>
                        @endif
                    </div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover datatable-custom">
                            <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th>Name</th>
                                <th class="text-center">NIK</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if($survey)
                                    @foreach($survey as $s)
                                    <tr>
                                        <td class="text-center text-muted">1</td>
                                        <td>
                                            <div class="widget-content p-0">
                                                <div class="widget-content-wrapper">
                                                    <div class="widget-content-left flex2">
                                                        <div class="widget-heading">{{$s->nama}}</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center">{{$s->nik}}</td>
                                        <td class="text-center">
                                            @if($s->status->id == 1)
                                                <div class="badge badge-secondary">
                                            @elseif($s->status->id == 2)
                                                <div class="badge badge-success">
                                            @else
                                                <div class="badge badge-danger">
                                            @endif
                                                {{$s->status->description}}
                                            </div>
                                        </td>
                                        <td class="text-center">
                                            @if(Auth::user() && Auth::user()->role_id == 2)
                                            <a href="{{route('survey.edit', $s->id)}}" class="btn badge badge-primary text-white">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            @endif
                                            <button type="button" class="btn badge badge-primary btn-detail-survey" data-survey-id="{{$s->id}}" 
                                            data-toggle="modal" data-target=".detail-survey">
                                                <i class="fa fa-eye"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

@endsection